//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     $DotRezCore.Api.Tests.Integration.ModelGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DotRezCore.Api.Tests.Integration.Models.V1
{
    public partial class City 
    {
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; } 
    }
}