//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     $DotRezCore.Api.Tests.Integration.ModelGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DotRezCore.Api.Tests.Integration.Models.V1
{
    public partial class GetOrderRequest 
    {
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public string Id { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "gender")]
        public DotRezCore.Api.Tests.Integration.Models.V1.Gender Gender { get; set; } 
    }
}
