//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     $DotRezCore.Api.Tests.Integration.ModelGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DotRezCore.Api.Tests.Integration.Models.V1
{
    public partial class Person 
    {
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public int? Id { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "email")]
        public string Email { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "city")]
        public DotRezCore.Api.Tests.Integration.Models.V1.City City { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "cities")]
        public System.Collections.Generic.List<DotRezCore.Api.Tests.Integration.Models.V1.City> Cities { get; set; } 
        [Newtonsoft.Json.JsonProperty(PropertyName = "gender")]
        public DotRezCore.Api.Tests.Integration.Models.V1.Gender? Gender { get; set; } 
    }
}
