version: "3"
networks:
  elastic-stack:

services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic-stack
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    depends_on:
      - elastic-search
    environment:
      - ELASTICSEARCH_URL=http://elastic-search:9200
    ports:
      - 5601:5601
    networks:
      - elastic-stack
