
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     $DotRezCore.Api.Tests.Integration.ModelGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------;
namespace DotRezCore.Api.Tests.Integration.ApiClients.V1
{
    public partial class PeopleClient 
    {
        private System.Net.Http.HttpClient _httpClient;
        private Newtonsoft.Json.JsonSerializerSettings _serializerSettings;
        private Microsoft.Extensions.Logging.ILogger<PeopleClient> _logger;
        public string XSessionToken { get; private set; } = string.Empty;
        public string DefaultCulture { get; } = "en-IE";
         
        public PeopleClient(System.Net.Http.HttpClient httpClient, Microsoft.Extensions.Logging.ILogger<PeopleClient> logger)
        {
            _httpClient = httpClient;
            _serializerSettings = new Newtonsoft.Json.JsonSerializerSettings();
            _logger = logger;
        }
        
        public async System.Threading.Tasks.Task<System.Collections.Generic.List<DotRezCore.Api.Tests.Integration.Models.V1.Person>> GetAsync()
        {
            return await GetAsync(XSessionToken);
        }
        public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> GetResponseAsync()
        {
            return await GetResponseAsync(XSessionToken);
        }
        
        public async System.Threading.Tasks.Task<System.Collections.Generic.List<DotRezCore.Api.Tests.Integration.Models.V1.Person>> GetAsync(string xsessiontoken)
        { 
            string content = string.Empty;
            try
            {
                var response = await GetResponseAsync(xsessiontoken);
                content = await response.Content.ReadAsStringAsync();
                var result = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.List<DotRezCore.Api.Tests.Integration.Models.V1.Person>>(content, _serializerSettings);
                return result;
            }
            catch(System.Exception ex)
            {
                Microsoft.Extensions.Logging.LoggerExtensions.LogError(_logger, default(Microsoft.Extensions.Logging.EventId), ex, "There was an error while making a API call. Response content is {0}", content);
                throw;
            }
        }
        
        public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> GetResponseAsync(string xsessiontoken)
        {
            using(var httpRequestMessage = new System.Net.Http.HttpRequestMessage())
            {
                var urlStringBuilder = new System.Text.StringBuilder("api/People");
                httpRequestMessage.Method = new System.Net.Http.HttpMethod("GET");
                httpRequestMessage.RequestUri = new System.Uri(urlStringBuilder.ToString(), System.UriKind.RelativeOrAbsolute);
                httpRequestMessage.Headers.Add("X-Session-Token", xsessiontoken);
                var response = await _httpClient.SendAsync(httpRequestMessage);
                response.EnsureSuccessStatusCode();
                if(response.Headers.TryGetValues(DotRezCore.Api.Constants.Session.XSessionTokenHeaderName, out var sessionTokenHeaders))
                {
                    XSessionToken = System.Linq.Enumerable.First(sessionTokenHeaders);
                }
                return response;
            }
        }
        
        public async System.Threading.Tasks.Task<DotRezCore.Api.Tests.Integration.Models.V1.Person> ByIdGetAsync(int id)
        {
            return await ByIdGetAsync(id, XSessionToken);
        }
        public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> ByIdGetResponseAsync(int id)
        {
            return await ByIdGetResponseAsync(id, XSessionToken);
        }
        
        public async System.Threading.Tasks.Task<DotRezCore.Api.Tests.Integration.Models.V1.Person> ByIdGetAsync(int id, string xsessiontoken)
        { 
            string content = string.Empty;
            try
            {
                var response = await ByIdGetResponseAsync(id, xsessiontoken);
                content = await response.Content.ReadAsStringAsync();
                var result = Newtonsoft.Json.JsonConvert.DeserializeObject<DotRezCore.Api.Tests.Integration.Models.V1.Person>(content, _serializerSettings);
                return result;
            }
            catch(System.Exception ex)
            {
                Microsoft.Extensions.Logging.LoggerExtensions.LogError(_logger, default(Microsoft.Extensions.Logging.EventId), ex, "There was an error while making a API call. Response content is {0}", content);
                throw;
            }
        }
        
        public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> ByIdGetResponseAsync(int id, string xsessiontoken)
        {
            using(var httpRequestMessage = new System.Net.Http.HttpRequestMessage())
            {
                var urlStringBuilder = new System.Text.StringBuilder("api/People/{id}");
                urlStringBuilder.Replace("{id}", System.Uri.EscapeDataString(ConvertToString(id, System.Globalization.CultureInfo.InvariantCulture)));
                httpRequestMessage.Method = new System.Net.Http.HttpMethod("GET");
                httpRequestMessage.RequestUri = new System.Uri(urlStringBuilder.ToString(), System.UriKind.RelativeOrAbsolute);
                httpRequestMessage.Headers.Add("X-Session-Token", xsessiontoken);
                var response = await _httpClient.SendAsync(httpRequestMessage);
                response.EnsureSuccessStatusCode();
                if(response.Headers.TryGetValues(DotRezCore.Api.Constants.Session.XSessionTokenHeaderName, out var sessionTokenHeaders))
                {
                    XSessionToken = System.Linq.Enumerable.First(sessionTokenHeaders);
                }
                return response;
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value is System.Enum)
            {
                string name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute)) as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value;
                        }
                    }
                }
            }
            return System.Convert.ToString(value, cultureInfo);
        }
    
        private string SerializeToQueryString(object request)
        {
            return string.Join("&", System.Linq.Enumerable.Select(request.GetType().GetProperties(), property => $"{property.Name}={System.Uri.EscapeDataString(property.GetValue(request).ToString())}"));
        }
    }
}
