using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorLight;

namespace DotRezCore.Api.Tests.Integration.ModelGenerator.Extensions
{
    public static class TemplatePageExtensions
    {
        private static readonly string GeneratorName = typeof(TemplatePageExtensions).Assembly.GetName().Name;
        
        public static HtmlString FileHeader(this TemplatePage myHelper)
        {
            return new HtmlString($@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ${GeneratorName}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------");
        }
    }
}